# Generated by Django 3.2.4 on 2021-07-03 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dionica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rb', models.IntegerField(blank=True, default=0, null=True, verbose_name='Redni broj')),
                ('naziv', models.CharField(max_length=50, null=True)),
                ('duzina', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dužina(m)')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dionice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mjesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tvrtka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poslodavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.tvrtka')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podrucje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=100, null=True)),
                ('dc', models.CharField(blank=True, max_length=5, null=True, verbose_name='DČ')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podrucja', to=settings.AUTH_USER_MODEL)),
                ('mjesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podrucja', to='backbone.mjesto')),
            ],
        ),
        migrations.CreateModel(
            name='Odk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=5)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('izvodjac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.tvrtka')),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Riješeno', 'Riješeno'), ('Zastoj', 'Zastoj'), ('U izvođenju', 'U izvođenju')], default='U izvođenju', max_length=20)),
                ('pocetna', models.IntegerField(blank=True, default=0)),
                ('zavrsna', models.IntegerField(blank=True, default=0)),
                ('radna_duzina', models.IntegerField(blank=True, default=0)),
                ('broj_niti', models.IntegerField(blank=True, default=0, null=True)),
                ('napomena', models.CharField(blank=True, max_length=100, null=True)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('zadnje_azuriranje', models.DateTimeField(auto_now=True)),
                ('zavrseno_datum', models.DateTimeField(null=True)),
                ('rijeseno', models.BooleanField(default=False)),
                ('azurirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dionica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kablovi', to='backbone.dionica')),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('odk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.odk')),
                ('zavrsio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dionica',
            name='podrucje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dionice', to='backbone.podrucje'),
        ),
        migrations.CreateModel(
            name='Biljeska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.CharField(blank=True, max_length=2000, verbose_name='Bilješka')),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('kabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biljeske', to='backbone.kabel')),
                ('kreirao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-kreirano'],
            },
        ),
    ]
