# Generated by Django 3.2.4 on 2021-07-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabel',
            name='odk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kablovi', to='backbone.odk'),
        ),
        migrations.AlterField(
            model_name='odk',
            name='naziv',
            field=models.CharField(max_length=6),
        ),
    ]
