# Generated by Django 3.2.4 on 2021-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0003_alter_zaposlenik_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='podrucje',
            name='je_uvezeno',
            field=models.BooleanField(default=False),
        ),
    ]
