# Generated by Django 3.2.4 on 2021-08-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0004_podrucje_je_uvezeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odk',
            name='izvodjac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.tvrtka'),
        ),
    ]
