# Generated by Django 3.2.4 on 2021-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0005_alter_odk_izvodjac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odk',
            name='naziv',
            field=models.CharField(max_length=50),
        ),
    ]
