# Generated by Django 3.2.4 on 2021-08-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0006_alter_odk_naziv'),
    ]

    operations = [
        migrations.AddField(
            model_name='odk',
            name='podrucje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odks', to='backbone.podrucje'),
        ),
    ]
