# Generated by Django 3.2.4 on 2021-08-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0007_odk_podrucje'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='kabel',
            order_with_respect_to='dionica',
        ),
    ]
