# Generated by Django 3.2.4 on 2021-08-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0008_alter_kabel_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='kabel',
            order_with_respect_to=None,
        ),
    ]
